### ISSUE TITLE
Share helper functions between connection and transform

### ISSUE THREAD

**Issue by davidarcher** [salesforce/refocus-sample-generator-template-utils#35]
Is there an easy way to share code between the transform.js and connection.js files?

My use case is that I have a giant switch statement in connection.js that looks at the subject and aspect and generates a custom query to our monitoring system. I want to be able to generate that same custom query when I create the sample object in transform.js (specifically, I want to set it as a relatedLink in the sample object) without having to manually duplicate the same helper functions in each file.

**Comment by iamigo** [comment]
Yes! Yes! Yes!

@jgraff2 I seem to remember us talking about this... did you ever implement this?

**Comment by davidarcher** [comment]
OK, I figured out that if i create a `helpers/helpers.js` file in the root and replace the explicit definition in the transform.js with `helpers: require('../helpers/helpers')`, it builds fine and includes the helpers.

Maybe change the comment telling folks "don't require any other modules" because that made me not even think of the simple approach here?

https://github.com/salesforce/refocus-sample-generator-template-utils/blob/master/prototype/connection/connection.js#L10
